---
- hosts: all
  remote_user: ubuntu
  sudo: yes
  tasks:
    - name: "cp prepare.sh"
      copy:
        src: prepare.sh
        dest: /home/ubuntu/prepare.sh

    - name: "cp install.sh"
      copy:
        src: prepare.sh
        dest: /home/ubuntu/prepare.sh

    - name: "initiate server"
      command: sh /home/ubuntu/prepare.sh
      
    - name: "install couchdb"
      command: sh /home/ubuntu/install.sh

- hosts: masterdb
  remote_user: ubuntu
  sudo: yes
  tasks:
    - name: "setup cluster"
      command: sh /home/ubuntu/cluster_setup.sh
