#
# ========================= COMP90024 TEAM 16 =========================
#
# 889545   Yu Liu          yul22       yul22@student.unimelb.edu.au
# 875095   Jize Dong       jized       jized@student.unimelb.edu.au
# 911764   Minsheng Wang   minshengw   minshengw@student.unimelb.edu.au
# 890742   Minglun Zhang   minglunz    minglunz@student.unimelb.edu.au
# 905084   Xingping Ding   xingpingd   xingpingd@student.unimelb.edu.au
#
# =====================================================================
#

---
- hosts: harvesters
  remote_user: ubuntu
  sudo: yes
  tasks:
  - name: install screen
    apt:
      name: screen

  - name: install pip
    apt:
      name: python-pip

  - name: pip install couchdb
    command: pip install couchdb

  - name: pip install tweepy
    command: pip install tweepy

  - name: pip install textblob
    command: pip install -U textblob
    
  - name: textblob download corpora
    command: python -m textblob.download_corpora

  - name: pip install shapely
    command: pip install shapely

  - name: pip install fiona
    command: pip install fiona